# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Ye9aOS0eKsFKEC3ReOiH1du4gYCVHiK
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import PyPDF2
# import nltk
# import re
# 
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.metrics.pairwise import cosine_similarity
# 
# nltk.download('stopwords')
# from nltk.corpus import stopwords
# 
# def extract_text_from_pdf(pdf_file):
#     text = ""
#     reader = PyPDF2.PdfReader(pdf_file)
#     for page in reader.pages:
#         text += page.extract_text()
#     return text
# 
# def clean_text(text):
#     text = text.lower()
#     text = re.sub(r'[^a-zA-Z ]', '', text)
#     text = text.split()
#     text = [word for word in text if word not in stopwords.words('english')]
#     return " ".join(text)
# 
# def calculate_similarity(resume_texts, jd_text):
#     documents = resume_texts + [jd_text]
#     vectorizer = TfidfVectorizer()
#     tfidf_matrix = vectorizer.fit_transform(documents)
#     similarity_scores = cosine_similarity(
#         tfidf_matrix[:-1], tfidf_matrix[-1]
#     )
#     return similarity_scores.flatten()
# 
# st.set_page_config(page_title="AI Resume Screening System")
# 
# st.title("🧠 AI Resume Screening System")
# 
# uploaded_files = st.file_uploader(
#     "Upload Resume PDFs",
#     type=["pdf"],
#     accept_multiple_files=True
# )
# 
# job_description = st.text_area("Paste Job Description")
# 
# if st.button("🔍 Screen Resumes"):
#     if not uploaded_files or job_description.strip() == "":
#         st.warning("Please upload resumes and enter job description")
#     else:
#         resumes = []
#         resume_names = []
# 
#         for file in uploaded_files:
#             text = extract_text_from_pdf(file)
#             cleaned_text = clean_text(text)
#             resumes.append(cleaned_text)
#             resume_names.append(file.name)
# 
#         cleaned_jd = clean_text(job_description)
#         scores = calculate_similarity(resumes, cleaned_jd)
# 
#         results = sorted(
#             zip(resume_names, scores),
#             key=lambda x: x[1],
#             reverse=True
#         )
# 
#         st.subheader("📊 Resume Match Results")
#         for name, score in results:
#             st.write(f"📄 {name} — **{round(score*100,2)}% match**")

!ls

!pip install streamlit

!pkill streamlit

!apt-get update
!apt-get install -y cloudflared

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &

!cloudflared tunnel --url http://localhost:8501
